### ISSUE TITLE
Separate Outbox storage into 2 classes

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus.NHibernate#102]
Core Issue: https://github.com/Particular/NServiceBus/issues/2659
Core PR: https://github.com/Particular/NServiceBus/pull/2734
Working in branch splitting-outbox-storage

I seem to be hung up because the Updating_to_v6_core branch doesn't appear to take a few things into account yet, notably deprecation of UniqueAttribute.

@johnsimons can you please comment?

**Comment by johnsimons** [comment]
Yep that branch is not up to date, it shouldn't be difficult to update it
to latest, if u need any help ping me

**Comment by SzymonPobiega** [comment]
It is unlikely we'll do any major design changes in the NH persistence given we have SQL persistence.
