### ISSUE TITLE
Consider turning off pessimistic concurrency when user specifies `[RowVersion]`

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.NHibernate#103]
The current behavior is even if a user specified `[RowVersion]` with an intention to switch to optimistic concurrency control, the resulting SQL statement contains the `UPDLOCK` hint.

I think it would be more natural to switch to read lock in that case.

**Comment by ramonsmits** [comment]
@SzymonPobiega When using RowVersion the user expects to have concurrent reads on the same aggregate instance. Having an update lock would prevent that from happening.

I don't know why we explicitly set a LockMode as AFAIK NHibernate chooses the right lock type depending if your entity has versioning enabled to allow for optimistic concurrency control.

I think specifying anything higher then a read lock doesn't make sense unless you are 100% sure then handling a message will result in delete or update.

IMHO we shouldn't set a LockMode at all unless explicitly configured by the user and rely on NHibernate its default handling

Even a read lock wouldn't make sense due NHibernate its 1st level cache as that would apply a read lock while transaction isolation level is set to read uncommitted.

**Comment by SzymonPobiega** [comment]
@ramonsmits I believe the update lock prevents another thread from trying to process another message that is directed to same saga instance. Such a behavior would result in one of the threads getting concurrency exception and one of the messages would be retried.

**Comment by SzymonPobiega** [comment]
This would be a breaking change and I no longer believe this would be a desirable feature.
