### ISSUE TITLE
NHibernate has a security vulnerability 

### ISSUE THREAD

**Issue by dickerstu** [Particular/NServiceBus.NHibernate#1146]
#### Description
There is a security advisory with the version of NHibernate that is currently being used.
https://github.com/nhibernate/nhibernate-core/security/advisories/GHSA-fg4q-ccq8-3r5q

#### Versions

Please list the version of the relevant packages or applications in which the bug exists.        

### Steps to reproduce

Build the project with Github Actions.

#### Possible solutions
Update NHibernate to 5.4.9 or 5.5.2

**Comment by NChaganlal** [comment]
Hi @dickerstu,

I noticed that you closed this issue, was this a mistake?

**Comment by NChaganlal** [comment]
Re-opening the issue for further clarification.

**Comment by dickerstu** [comment]
There is a pull request to address the vulnerability.

**Comment by NChaganlal** [comment]
Connecting the dots: https://github.com/Particular/NServiceBus.NHibernate/pull/1145

**Comment by NChaganlal** [comment]
@dickerstu We've addressed the vulnerability, please see the following [announcement](https://discuss.particular.net/t/nservicebus-nhibernate-10-0-1-9-0-3-and-8-6-4-security-patch-releases-available/4046).
