### ISSUE TITLE
Make the timeout persister use existing connection if found

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.NHibernate#116]
Given that v6 no flows the context properly we can modify the TM persister looks for existing connections similar to how we do it for the outbox.

This would avoid DTC use when running on top of the sql transport

**Comment by SzymonPobiega** [comment]
I am pretty sure it works like that:
 * https://github.com/Particular/NServiceBus.NHibernate/blob/develop/src/NServiceBus.NHibernate/TimeoutPersisters/TimeoutPersister.cs#L82
 * https://github.com/Particular/NServiceBus.NHibernate/blob/develop/src/NServiceBus.NHibernate/SharedSession/DbConnectionProvider.cs

**Comment by andreasohlund** [comment]
Ah, I see that now!

Must learn to check the code before raising issues :)
