### ISSUE TITLE
Filter out dispatched outbox messages

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.NHibernate#118]
Currently we are not filtering out already dispatched transport operations. This creates unessesary downstream duplicates when a messages id deduped by the outbox.

We should modify

https://github.com/Particular/NServiceBus.NHibernate/blob/develop/src/NServiceBus.NHibernate/Outbox/OutboxPersister.cs#L45

to only return non dispatched transport operations to prevent this from happening.

In essense we would return an empty list to the core if all the ops have been dispatched

**Comment by SzymonPobiega** [comment]
Fixing this in the hotfix here https://github.com/Particular/NServiceBus.NHibernate/commit/e30acd748a7df1b60051fe913535a4000b0cf3cc. 

@andreasohlund @Particular/nservicebus please review
