### ISSUE TITLE
Verify performance when endpoints share storage tables

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.NHibernate#121]
The usual perf tests we do only focus on a single endpoint. We need to check performance when multiple endpoints share the same storage table (timeouts, subscriptions, and soon Outbox).

cc @johnsimons @udidahan

**Comment by SzymonPobiega** [comment]
@andreasohlund I am pretty sure this issue is a bit outdated. I home you don't mind me closing it ;-)
