### ISSUE TITLE
Async/Await support

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.NHibernate#138]
Task force: @SzymonPobiega @DavidBoike 

Connects to Particular/PlatformDevelopment#182
Connects to https://github.com/Particular/NServiceBus/issues/3126

This is the NHibernate adapter epic which incorporates the work for making the NHibernate adapter async/await enabled. Please see [this blog post](http://particular.net/blog/async-await-its-time) about the reasoning behind it.

**Comment by andreasohlund** [comment]
I'm not working on this, last I heard @SzymonPobiega was looking at this?

**Comment by HEskandari** [comment]
There's #146 to take care of, plus investigating why some of the ATT tests are unstable on TeamCity. Then we should be able to close off this epic.

**Comment by WojcikMike** [comment]
@SzymonPobiega is the Task Force still working on it? Is it blocked as @HEskandari described? In which case can we mark it as blocked? 

Who is working on ATT being unstable? @HEskandari are you working on them?

**Comment by SzymonPobiega** [comment]
@HEskandari #146 is now only V5-focused as I already implemented similar feature for V6. I think we can close this one now.

**Comment by HEskandari** [comment]
There's a minor change and documentation that's being finalized (#175 and the [docs PR][1]) and then we can close this one.

[1]: https://github.com/Particular/docs.particular.net/pull/1299

**Comment by danielmarbach** [comment]
@HEskandari since the outstanding work is tracked by the linked issues and they are merged I'm closing this one.
