### ISSUE TITLE
Disabling distributed transactions causes InvalidCastException

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.NHibernate#142]
When disabling distributed transactions (`.Transactions().DisableDistributedTransactions()`) resolving the current transaction via `NHibernateStorageContext.DatabaseTransaction` results in the following InvalidCastException:

>System.InvalidCastException: Unable to cast object of type 'NHibernate.Transaction.AdoTransaction' to type 'System.Lazy`1[NHibernate.ITransaction]'.
   at NServiceBus.Pipeline.BehaviorContext.TryGet[T](String key, T& result) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorContext.cs:line 72
   at NServiceBus.Persistence.NHibernate.NHibernateStorageContext.get_DatabaseTransaction() in C:\BuildAgent\work\5135de308b2f3016\src\NServiceBus.NHibernate\NHibernateStorageContext.cs:line 46

## Cause

It seems the incorrect type is set in the context:

    var tx = session.BeginTransaction();
    context.Set(LazyNHibernateTransactionKey, tx);

- https://github.com/Particular/NServiceBus.NHibernate/blame/master/src/NServiceBus.NHibernate/SharedSession/OpenSessionBehavior.cs#L73

## Solution

This probably need to be either of the following:

    var tx = session.BeginTransaction();
    var lazyTx = new Lazy<ITransaction>(() => tx);
    context.Set(LazyNHibernateTransactionKey, lazyTx);

or

    var lazyTx = new Lazy<ITransaction>(() => session.BeginTransaction());
    context.Set(LazyNHibernateTransactionKey, lazyTx);

I'm not sure what the behavior should be like or why it even is lazy initialized.

**Comment by ramonsmits** [comment]
@SzymonPobiega Please check this issue. I've created a patch in the hotfix-6.2.6 branch and that seems to work but I don't know if that is the correct behavior.

**Comment by SimonCropp** [comment]
Is a patch really required here? Cant this wait till the next major of NH?

**Comment by ramonsmits** [comment]
@SimonCropp Next major version is probably targeting NServiceBus v6. Current version does not allow to share the same connection as persistence when having distributed transactions disabled. Have not tested yet if this is only the case with SQL transport.

I created the hotfix to test if it would make the sample run in that configuration to confirm my assumption about its behavior.
