### ISSUE TITLE
TimeoutPersister should use '>' rather than '>=' when applying slice predicate

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus.NHibernate#145]
Currently the `TimeoutPersister` uses the following predicate to filter out timeouts:
```
 .And(x => x.Time >= startSlice && x.Time <= now)
```
https://github.com/Particular/NServiceBus.NHibernate/blob/develop/src/NServiceBus.NHibernate/TimeoutPersisters/TimeoutPersister.cs#L40

`ExpiredTimeoutsPoller` issues queries against `IQueryTimeouts` with the oldest of timeouts returned in the previous query. Having that logic combined with the predicate above, results in possibility of duplicates, when two succeeding queries are issued before the timeout entity is deleted. For instance:
* EpiredTimeoutsPoller queries with the initial startSlice 
* TimeoutPersister returns timeouts with times d1, d2, d3
* EpiredTimeoutsPoller saves d3 as the next startSlice, later on queries again
* TimeoutPersister is queried with d3, returning the timeout with d3 again.

That predicate is different from one in 'InMemoryTimeoutPersister' which uses '>', see: https://github.com/Particular/NServiceBus/blob/48cad8bbd3c2e0fff4ec6b6abd084c0b78b7bbd8/src/NServiceBus.Core/Persistence/InMemory/TimeoutPersister/InMemoryTimeoutPersister.cs#L110

**Comment by Scooletz** [comment]
+ @timbussmann

**Comment by SzymonPobiega** [comment]
@Scooletz what is the severity of this bug? Are we missing timeouts because of it?

**Comment by Scooletz** [comment]
My reasoning was following. If a single timeout is retrieved, its date will be used as another `startSlice`. If the dispatch does not happen before the next round (for any reason) the timeout will be obtained again. I do remember though that there were some discussions about how timeouts are handled, so this reasoning may be no longer valid.

**Comment by bording** [comment]
@Particular/nhibernate-persistence-maintainers FYI NHibernate is now the only v6 persistence that hasn't yet updated to to using `>` instead of `>=`.  We really should be consistent here. Any chance you can consider making this change before RTM?
