### ISSUE TITLE
Set TransportOperations to NULL when marking as dispatched

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.NHibernate#146]
Related fix: https://github.com/Particular/NServiceBus.NHibernate/tree/clear-transportoperations-when-dispatched

### Who's affected

Users of NSB 5.x

### Symptoms

We currently only mark the record as dispatched. When the record is deleted during cleanup this delete is expensive due to the nvarchar(max) due to the amount of locking required. This is not an issue when doing a single delete but the cleanup does a unbounded delete as this operation is database agnostic (we cannot tweak for SQL Server).

By deleting the TransportOperations data the cleanup delete requires less locking resulting in less IO when doing the unbounded cleanup delete query.

### Proposal

https://github.com/Particular/NServiceBus.NHibernate/blob/develop/src/NServiceBus.NHibernate/Outbox/OutboxPersister.cs#L92

From

```sql
update {typeof(OutboxRecord)}
set Dispatched = true
,DispatchedAt = :date
where MessageId IN ( :messageid, :qualifiedMessageId )
And Dispatched = false
```

To

```sql
update {typeof(OutboxRecord)}
set Dispatched = true
,DispatchedAt = :date
,TransportOperations = null
where MessageId IN ( :messageid, :qualifiedMessageId )
And Dispatched = false
```

**Comment by ramonsmits** [comment]
As I was affected by this when doing a stress test I made this change in ff0cb11 can we consider a hotfix for this?

**Comment by andreasohlund** [comment]
Looks like ravendb has the same issue.

@Particular/persistence-maintainers I think we need to triage this since we might need to hotfix

**Comment by DavidBoike** [comment]
I would think the severity of this is low, and there's no possibility of data loss. On the other hand it is probably a 1-line fix.

**Comment by andreasohlund** [comment]
The thing that could make it a "patch" would be the added disk usage. Do we have any numbers?

**Comment by ramonsmits** [comment]
@andreasohlund Lets assume that the customer is using the default window

I just queried my databases and had one outboxrecord table containing transportoperations.

Single record, single operation consumed 1001 characters so 2002 bytes. This is a single operation

Lets make some assumptions:

-  Dedupe window: 7 days
- Average throughput: 100 msg/s
- Average message send count on receive: 0.25
- Size of single transport message: 2.000 bytes

Size consumed by transportoperations column:

    7 * 24 * 3600 * 100  / 1024 / 1024 / 1024 * 0.25 * 2000 = ~28.2 GB

Remaining data 85 bytes:

- ID (bigint, 8 bytes)
- MessageID (nvarchar, [~72 bytes](https://github.com/Particular/NServiceBus.NHibernate/issues/169))
- Dispatched (bit, 1 byte)
- DispatchedAt (datetime, 4 byte)

Size consumed by other data:

    7 * 24 * 3600 * 100  / 1024 / 1024 / 2014 * 85 = ~2.4GB

Excluding indes size.


So this is 30.6 (28.2+2.4)GB vs 2.4GB, this is more then a factor 10 which is quite a huge difference. but we can tweak these numbers.

**Comment by andreasohlund** [comment]
Thanks @ramonsmits , do we say this is a patch based on these numbers?

Flagging this as core v6 since I think we should definitely fix this for that release

**Comment by ramonsmits** [comment]
To be honest, this whole discussion has taken me more time then releasing this as a patch. I think this is the good thing even for V5 as this has a huge impact on storage size.

**Comment by ramonsmits** [comment]
By the way, this impacts #148 , clearing the transport operation results in a much easier to perform deletes by SQL as it will be less likely to escalate to page or table locks.

**Comment by WojcikMike** [comment]
* What is the plan of attack for this issue?
* Why @SzymonPobiega is assigned to it? (he self assigned himself 9 days ago)

I am asking as I would gladly take it but I am not completely sold what should be done.

**Comment by SzymonPobiega** [comment]
@WojcikMike the current state is that change has been applied in the V6 version. It has been debated if this should be applied to V5 as a patch. @WojcikMike if you feel like releasing NHibernate, you are free to proceed.

**Comment by SzymonPobiega** [comment]
Removing the V6 label as it has already been done in develop.

**Comment by adamralph** [comment]
@SzymonPobiega there's no need to remove the label after the issued is closed. If it's part of the V6 Launch project then that doesn't change when it is closed.

**Comment by SzymonPobiega** [comment]
@adamralph OK. This one still has it: https://github.com/Particular/NServiceBus.NHibernate/pull/176

**Comment by SzymonPobiega** [comment]
@WojcikMike @ramonsmits if you feel like releasing it in 6 major makes sense, feel free to re-open this.
