### ISSUE TITLE
RegisterManagedSessionInTheContainer seems to be a no-op

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.NHibernate#152]
it sets a value that doesnt seem to be used. also has no tests

**Comment by SimonCropp** [comment]
@HEskandari  perhaps this should be the same as ravendb in that it can be retrieved from the context and not IOC?

https://github.com/Particular/NServiceBus.RavenDB/issues/151

**Comment by SimonCropp** [comment]
so it seems this method is replaced by 

```
    public async Task Handle(OrderSubmitted message, IMessageHandlerContext context)
    {
        Console.WriteLine("Order {0} worth {1} submitted", message.OrderId, message.Value);

        #region StoreUserData

        ISession nhibernateSession = context.SynchronizedStorageSession.Session();
        nhibernateSession.Save(new Order
        {
            OrderId = message.OrderId,
            Value = message.Value
        });
```

**Comment by HEskandari** [comment]
Can the ```RegisterManagedSessionInTheContainer``` method be obsoleted? @SzymonPobiega? Sent a PR.

**Comment by SzymonPobiega** [comment]
Yes, storage session is the way to go since we want to get rid of the container usage for NSB's stuff in the long run.

**Comment by HEskandari** [comment]
I couldn't find the PR for this...so planning to send a new one.

@SzymonPobiega could you confirm that the two methods should be obsoleted? I can't find anything related to ``UseCustomSessionCreationMethod`` and ``RegisterManagedSessionInTheContainer`` methods on configuration extension.

**Comment by SzymonPobiega** [comment]
Hmmm It would be nice if we could have `UseCustomSessionCreationMethod` in the new version but not sure if this is possible.

**Comment by HEskandari** [comment]
Currently I can see that there are SessionFactories created per feature, e.g. Storage Session, Gateway Deduplication, Subscription Storage and Timeout Persister.

How about if we have something to encapsulate SessionFactory and / or Session creation, and use that in all those places?

public interface IManageSessionFactory
{
   ISessionFactory CreateSessionFactory();
}

Would that be enough to give user the control over using their own ```ISession```? This can be registered / resolved directly in the container or provided through the ```Func``` via config API. What's the catch?

**Comment by SzymonPobiega** [comment]
So the 6.X `UseCustomSessionCreationMethod` seems wrong because you can't get the reference to the actual session factory so you are providing a session possibly missing mappings etc. There are config methods for providing `Configuration` object. I wonder if this is not enough? Or maybe we should have a hook like `InitSession` where we pass a fresh session and let users fiddle with it?

`RegisterManagedSessionInTheContainer` should be obsoleted based on the general guidance that NSB-managed stuff should be provided through the context.

**Comment by HEskandari** [comment]
@SzymonPobiega I have made both obsolete. As for custom session creation, think providing custom ```Configuration``` object would provide *some* benefits. I'm not sold on providing hook like ```InitSession``` though and not sure what benefit would that bring?

**Comment by SzymonPobiega** [comment]
@HEskandari true. Let's now do `InitSession`. Custom `configuration` is useful when you want to provide some additional mappings.

**Comment by SzymonPobiega** [comment]
@HEskandari I've found a case where some kind of "provide session" method might be useful -- multi tenant deployment. In such case we want to provide a session based on the message (probably headers). But we can address this in a minor release following 7.0.

**Comment by mikeminutillo** [comment]
Is this one waiting on https://github.com/Particular/NServiceBus.NHibernate/pull/175 ? What needs to be done to close this issue? Can you add a Plan of Attack to the issue?

**Comment by HEskandari** [comment]
@mikeminutillo yes, once we close/merge #175 and the [docs PR][1] this is effectively done.

[1]: https://github.com/Particular/docs.particular.net/pull/1299

**Comment by boblangley** [comment]
@HEskandari it looks like both of those are merged. Can we close?

**Comment by HEskandari** [comment]
@boblangley agreed. Closing it now.
