### ISSUE TITLE
Build status for acpt tests builds are not feed back to GitHub

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.NHibernate#162]
The "GH feedback" feature seems to be missing

https://builds.particular.net/admin/editBuildFeatures.html?id=buildType:NServiceBusNHibernate_2AcceptanceTests

This causes eg. https://github.com/Particular/NServiceBus.NHibernate/pull/159 to show up green but there is loads of failing tests

**Comment by SzymonPobiega** [comment]
I'll migrate to `StandardBuildV3` so that the acceptance tests are executed in the build step.

**Comment by SzymonPobiega** [comment]
Works.
