### ISSUE TITLE
Store transport operations as NTEXT instead of NVARCHAR(MAX)

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.NHibernate#170]
As transport operations as usually just stored very briefly. The current approach would live large 'gaps' in data pages if removing of nulling transport operations when the messages are dispatched.

By using NTEXT we force SQL to store the transport operations in a different data page.

The result is more compact outboxrecord records that needs less maintenance and results in less defragmentation.

**Comment by DavidBoike** [comment]
From [MSDN](https://msdn.microsoft.com/en-us/library/ms187993.aspx):

> ntext, text, and image data types will be removed in a future version of Microsoft SQL Server. Avoid using these data types in new development work, and plan to modify applications that currently use them. Use nvarchar(max), varchar(max), and varbinary(max) instead.

nvarchar(max) is stored differently than a nvarchar(really-big-number). An nvarchar(max) will store the data inline in the page if it's "short enough" and if it's large enough, shuttle it off to a different page the same way ntext does. It's kind of a best-of-breed.

Closing as Won't Fix.

**Comment by ramonsmits** [comment]
@DavidBoike Fair decision, didn't knew that NTEXT. Then the most obvious improvement would be to not store it in the same table. Thoughts?

**Comment by DavidBoike** [comment]
I think you're trying to out-optimize SQL Server. Storing it in a separate table is essentially what nvarchar(max) will do on disk level but a lot more efficiently. But an actual separate table would be more likely to result in lock escalation.

Would rather focus on #146 (subject to prio) if you're worried about cleanup.
