### ISSUE TITLE
Improve unreliable acceptance tests

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.NHibernate#173]
Following tests are failing now and then:
 * MutingHandlerExceptions.RunDemo 	
 * When_sending_to_slr.Should_raise_FinishedMessageProcessing_event 	
 * When_reply_from_a_finder.Should_be_received_by_handler 	

I looks that they pass/fail in non-deterministic way.

**Comment by SzymonPobiega** [comment]
I haven't seen any of these fail recently so closing this one.
