### ISSUE TITLE
Support storing saga data in serialized form

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.NHibernate#177]
Because of [this issue](https://github.com/Particular/PlatformDevelopment/issues/686) we need to support storing saga data in serialized form (rather than in tables and columns). Here are some questions that need to be answered:
- What serialization library to use? RavenDB uses a customized Json.net so it seems like a natural choice but on the other hand we decided to move away from json.net and, if possible, use `JsonDataContractSerializer`
- Should we support "blob" and "relational" modes in the same time i.e. some saga types would be using "blob" and some "relational" mode?
- Because of significant difference in terms of license cost between RavenDB and SQL Server or Oracle (which are the two supported databases in NH persistence), should we consider supporting a more cost-effective relational database e.g. PostgreSQL?
- Should the new "blob" mode be default in V6? If so, should we require explicit user-provided mappings when selecting non-blob mode?

**Comment by SzymonPobiega** [comment]
@HEskandari I put together a short list of questions that need to be answered in order to build this blob thing. Am I missing something?

**Comment by johnsimons** [comment]
Did @SzymonPobiega just added the V6 label to this :scream:

**Comment by SzymonPobiega** [comment]
@johnsimons based on https://github.com/Particular/PlatformDevelopment/issues/686 there is no option to not deliver this as part of V6. See this issue as an extension of 686 in this repo and since 686 has been approved and marked as critical I don't see a reason to go through the same process for all the subtasks of 686.

**Comment by SzymonPobiega** [comment]
@johnsimons scratch :point_up:, you're right. Since we have not decided if we are using @SimonCropp 's SQL persistence or changing NH, this is not yet "V6 approved".

**Comment by HEskandari** [comment]
- I'm good with using `JsonDataContractSerializer`. Although performance was a concern when compared to other options (@tmasternak ran the tests), is that perf test relevant here?

- On supporting both Relational and / or Blob, think we need to think about the trade offs.
  - Supporting both: 
     Pros: backwards compatible, more easily queryable, less headache for people moving to v6, not much difference in terms of effort (just a configuration)
     Cons: More code to manage

  - Going with Blob only:
     Pros: Similar to Sql Transport, one model to rule them all (simplicity)
     Cons: Not sure about performance aspects with large saga data, wouldn't integrate well with dev-ops tools, not easily queryable

So to answer, I believe supporting both options would be the best option at this stage.

- On supporting other relational databases, I like that, but could that be tackled separately?

- To keep the out of the box behavior same as before (well as much as possible), I'd suggest making the blob mode opt-in, not the default.

**Comment by tmasternak** [comment]
@HEskandari the end [decission](https://github.com/Particular/NServiceBus.SqlServer/pull/152#issuecomment-179807132) was to go with `JsonDataContractSerialier` which looks to be good enough and provide extension point in the future for users to register custom seirlizer if they need better performance.

**Comment by SzymonPobiega** [comment]
What I am afraid with regards to `JsonDataContractSerialier` is that it might behave differently is some odd scenarios. Keep in mind that messages are usually far simpler than sagas, especially if the saga data classes are generated by ServiceMatrix.

**Comment by tmasternak** [comment]
@SzymonPobiega good point. In SqlTransport we where using it only for header serialization wich is simple Dictionary.Of(string, string)

**Comment by HEskandari** [comment]
Is there a way to test that? We probably need some customer's databases (also to write and test the migration tool), can we test `JsonDataContractSerialier` on some of those databases to see what odd scenarios are and how it might behave?

**Comment by SzymonPobiega** [comment]
Yeah, some real data would be good. I know for sure that inheritence handling is different in these two serializers (the name of the meta-property that contains the real type name of the object). Probably handling of "weird" types need to be check (dates, times, decimal/float numbers, various strange collections etc.)

**Comment by SzymonPobiega** [comment]
We already have SQL persistence which uses json saga format. Closing this one.
