### ISSUE TITLE
Minimize public API surface area

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus.NHibernate#178]
For VNext, add APIApprover test and minimize surface area of the public API.

Must be `Project: V6 Launch` otherwise it will be too late.

See https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/56#issuecomment-200855259

Connects to https://github.com/Particular/PlatformDevelopment/issues/762

**Comment by SzymonPobiega** [comment]
@DavidBoike I've created a PR #179  that adds the approval tests. What else needs to be done to close this?

**Comment by SimonCropp** [comment]
I imagine go through every public api and confirm it should actually public. As a rule of thumb: if it is not documented it should not be public

**Comment by andreasohlund** [comment]
Connected this to https://github.com/Particular/PlatformDevelopment/issues/762
