### ISSUE TITLE
Nuget package of beta0003 fails to resolve.

### ISSUE THREAD

**Issue by janpieterz** [Particular/NServiceBus.NHibernate#193]
So this is odd, maybe a weird config setting locally, but while installing version 7.0.0-beta0003 of this package:

`Package 'NServiceBus.6.0.0-unstable0257' is not found on source 'https://api.nuget.org/v3/index.json'.	`
The pacakge references `NServiceBus (>= 6.0.0-beta0003 && < 7.0.0)` which is already odd since beta0003 isn't on nuget yet,

beta0002 doesn't exist for NHibernate, so I'm going with 0001 now.

Are you guys by any chance doing a rollout?

**Comment by timbussmann** [comment]
Hi @janpieterz 

Beta3 of NServiceBus is not pushed to NuGet yet (but will soon be), seems like the NHibernate beta package was pushed a little bit too early and with the wrong beta number. As you noted correctly, it should have been beta2 of NHibernate.

Going with beta1 should work fine until beta3 of NServiceBus is out. If you don't want to wait, the beta3 package is available on the particular myget feed here: https://www.myget.org/F/particular/

Thanks for reporting this issue and sorry for the inconvenience!

**Comment by janpieterz** [comment]
Superb, thanks!
