### ISSUE TITLE
Publish performance in V6 betas lower with DTC enabled

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.NHibernate#215]
Publish performance is severely degraded in NServiceBus V6 beta on the Azure test configuration.

Blue = V5, Yellow = V6

![image](https://cloud.githubusercontent.com/assets/152998/18056244/668f191c-6e0b-11e6-95ce-4d26ebd478fb.png)

Source: http://deploy.particular.net:8000/en-US/app/search/persisters_fixture?form.nsb_version=V6&form.nsb_version=V5&form.persistence_kind=NHibernate&earliest=0&latest=

**Comment by ramonsmits** [comment]
> This is likely caused due to the subscription persistence to be participating in the distributed transaction.

I removed this, publishing is done outside of a transaction scope in this scenario and not within an incoming messages context.

**Comment by ramonsmits** [comment]
After some research of @SzymonPobiega and @danielmarbach it was found that the batch of message is being send sequentially. Reason for this is that the NHibernate persistence is not async but wrapped in an async interface.

The code creates a task for each publish invocation and aggregates these in a `List<Task>` and then does `Task.WhenAll(..)` and this results in sequential execution.

- This is the reason that Azure persistence is so much faster as that is a real async API and the `Task.WaitAll` works great.
- The InMemory persister has a similar issue.

**Comment by ramonsmits** [comment]
After diagnosing the issue isn't related to NHibernate being non async but by the design of the `NHibernateStorageSession` in V6. In V5 this was lazy resulting in a more lightweight processing of messages if it wasn't used for outbox, saga or custom user session storage. In V6 it seems to always be initialized and it enlists in an existing transaction scope.

By using the following persistence configuration I tested what the performance is for both SQL Azure and local MSSQL.

```c#
cfg.UsePersistence<InMemoryPersistence>();
cfg.UsePersistence<NHibernatePersistence,StorageType.Subscriptions>();
cfg.DisableFeature<NHibernateStorageSession>();
```

The results are added to the following sheet:
 - https://docs.google.com/spreadsheets/d/1OjK4QVMClj3CoYJFKqu6tI2eDwhVnhVzUjI9BEn4bws/edit#gid=0

The summary is:

TransactionMode.TransactionScope:
- from 909 to 1,141 msg/s (58%) and is also faster than V5 (7%).

TransactionMode.SendsAtomicWithReceive
- from 1,761 to 2,066 msg/s (17%) and also is faster than V5 (14%).


I'm not sure if this configuration hack represents the same increase in performance as when NHibernateStorageSession would be lazy but I think it's a potential performance boost that cannot be ignored.

**Comment by danielmarbach** [comment]
Nice finding!

**Comment by andreasohlund** [comment]
Given that no sagas is present and the outbox isn't enabled should the NH session be off by default?

**Comment by SzymonPobiega** [comment]
it is accessible via the context so making it off would cause exceptions. But I can try to make it lazy.

**Comment by SzymonPobiega** [comment]
Here's a PR for making the session lazy: https://github.com/Particular/NServiceBus.NHibernate/pull/221. @ramonsmits I think we can close this one and discuss the pros/cons of lazy session on the PR.

**Comment by ramonsmits** [comment]
Closing this because the reason for the difference in performance is found.
