### ISSUE TITLE
Messages are lost when message type names or endpoint names contain Unicode chars

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.NHibernate#224]
Originally raised on GG https://groups.google.com/d/msgid/particularsoftware/3c156278-502a-4d22-a4b7-47533d75c64c%40googlegroups.com?utm_medium=email&utm_source=footer

### Symptoms

A message is not published that should have been.

### Who's affected

Users using Unicode characters in message types or endpoint names.

### Root cause

Subscriber table uses `VARCHAR` in text columns.

**Comment by SimonCropp** [comment]
@Particular/nhibernate-persistence-maintainers my understanding of this is equates to data loss. ie someone subscribes to an endpoint or a message type that contains a unicode character. when it is queried it will not match hence no publish will occur. or do i misunderstand the issue?

**Comment by SzymonPobiega** [comment]
@SimonCropp Interesting problem. I'll validate the behavior because I am not sure at which stage the information gets lost.

**Comment by cremor** [comment]
NServiceBus.Persistence.Sql uses NVARCHAR(200), so I assume that should work for NServiceBus.NHibernate too?

**Comment by WojcikMike** [comment]
Released in version 8.4.4
