### ISSUE TITLE
No way to influence mapping for OutboxRecord & TimeoutEntity

### ISSUE THREAD

**Issue by Tsjunne** [Particular/NServiceBus.NHibernate#231]
At my current client the DBA's have certain convensions that need to be followed with regards to object names in the database.

It doesn't look like it is possible to change any mappings for the internal classes used.
I can identify the code doing the mapping in the codebase, but i see no way of overriding the behavior without branching the code.

**Comment by SzymonPobiega** [comment]
Indeed there is no way to influence these mappings. This is intentional to make sure everything works as expected. @Tsjunne what aspects would you like to change?

**Comment by Tsjunne** [comment]
Well, our DBA's follow certain naming convensions for tablenames.
But that's a debatable issue and not my place to decide.

What really bothers me is how the mapping for the OutboxRecord ID translates to Oracle.
Since the mapping is defined as native it revers to sequence generation. Since there is no way to specify the sequence name, it revers to 'hibernate_sequence' as default name. This is kind of a stretch to justify to DBA's.
Combined with the fact that the default sequence strategy is not very performant for high volume tables (some prefetch implementations perform a whole lot better), the resulting DB objects for Oracle are quite subpar.

Exposing the underlying types as public, so i could override the default with my own mapping, would alleviate these problems.
Or if there were some kind of naming policy that could be provided for tables and sequences, that would at least get the DBA's off my back.

**Comment by SzymonPobiega** [comment]
#234 is a proposed fix to this.
