### ISSUE TITLE
Gracefully handle concurrency errors with scaled-out subscribers

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus.NHibernate#232]
Scaled-out subscribers may cause concurrency errors (PK violation) during processing of subscription messages by the publisher.

These errors should be gracefully handled within the persister, as it is currently done RavenDB and ASP persisters:

https://github.com/Particular/NServiceBus.Persistence.AzureStorage/blob/develop/src/NServiceBus.Persistence.AzureStorage/Subscriptions/AzureSubscriptionStorage.cs#L62

https://github.com/Particular/NServiceBus.RavenDB/blob/develop/src/NServiceBus.RavenDB/Subscriptions/SubscriptionPersister.cs#L31

The faulty tests have all been moved to the `Acceptance tests - quarantine build configuration`.

**Comment by SimonCropp** [comment]
should this be bumped to the next patch so the other two features in 7.1 can be shipped?

**Comment by MarcinHoppe** [comment]
Thanks @SimonCropp, that's not a priority now (test have been moved to a better place).

**Comment by SzymonPobiega** [comment]
Fixed via cd786978f2e967acd143accb2b85a6316d6e5a67
