### ISSUE TITLE
OutboxCleaner.PerformCleanup tears down the endpoint

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.NHibernate#241]
It seems that a connection failure during `OutboxCleaner.PerformCleanup` will tear down the endpoint, as exceptions aren't catched and will bubble up to the executing thread. See the issue here: https://github.com/Particular/NServiceBus/issues/4293

Given the fact, that we use circuit breakers to handle persistence failures in other places (e.g. the timeout manager) before directly shutting down the endpoint, I think it would be reasonable to do the same with the cleanup task. It probably makes sense to still fail the endpoint after the cleanup task wasn't able to run for a specified amount of time (several hours?).

ping @Particular/nhibernate-persistence-maintainers 

### Plan of Attack

- [ ] Add a circuit breaker to the Outbox cleanup task: #242 
- [x] Decide on how to configure the time to wait before triggering the circuit breaker
- [ ] Update the doco
  - [ ] [Critical exception wait time](https://docs.particular.net/nservicebus/recoverability/critical-exception-for-timeout-outages)
  - [ ] [Outbox with NHibernate persistence](https://docs.particular.net/nservicebus/nhibernate/outbox)

**Comment by MarcinHoppe** [comment]
@timbussmann @ramonsmits @andreasohlund I agree this is a good change for 7.1 (added this issue to the milestone). Is there anything that makes this issue urgent?

**Comment by timbussmann** [comment]
I'll leave that classification to you. As far as I understand it, it can cause the endpoint to shut down earlier than any configured circuit breaker (e.g. is the SQL server is up again after 1.5 minutes, the timeout managers circuit breaker is not violated and the endpoint would recover, while the outbox cleanup task will tear down then endpoint). So theoretically this could be seen as a critical, but in most cases, fixing this would just postpone the endpoint shutdown by ~1 minute.

**Comment by andreasohlund** [comment]
I'd lean towards a patch for the reasons mentioned by Tim

**Comment by MarcinHoppe** [comment]
Thanks.

@HEskandari @SzymonPobiega What do you think about it?

**Comment by HEskandari** [comment]
I'm 👍 on the patch. If it crashes the endpoint, should be considered as critical IMO.

**Comment by MarcinHoppe** [comment]
We will still crash the endpoint, only later and not that often. I'm also 👍 on a patch.

**Comment by MarcinHoppe** [comment]
I created a mileston for the patch and assigned this issue to this new milestone.

**Comment by MarcinHoppe** [comment]
@Particular/nhibernate-persistence-maintainers I updated the PoA for this issue.

**Comment by HEskandari** [comment]
Did we update the documentation as per the PoA above? The last update date of those pages are two and three months ago respectively, which makes me think they are not updated?

**Comment by SzymonPobiega** [comment]
https://docs.particular.net/nservicebus/recoverability/critical-exception-for-timeout-outages this should be moved under the timeout manager and I don't think we need to touch it.

I'll add proper info to https://docs.particular.net/nservicebus/nhibernate/outbox.

**Comment by SzymonPobiega** [comment]
Well, it feels kind of awkward to document this by saying users are required to modify `NServiceBus/Outbox/NHibernate/TimeToWaitBeforeTriggeringCriticalErrorWhenCleanupTaskFails` application setting. Should we add a public extension method for setting this?

**Comment by MarcinHoppe** [comment]
@SzymonPobiega This is consistent with how other parameters for the Outbox cleaner are configured. I think we could add configuration in code as a separate issue to include in 7.1 release. It looks small enough to be handled by maintainers.

**Comment by SzymonPobiega** [comment]
@MarcinHoppe then i'd say defer the documentation until then and :shipit: 7.0.2 now?

**Comment by MarcinHoppe** [comment]
The code-first configuration API for the circuit breaker will be released as part of the 7.1 milestone. We will defer documentation until release.
