### ISSUE TITLE
Incorrect schema creation for timeout entity causes performance degradation

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.NHibernate#252]
### Who's affected

Users of NHibernate persistence who pass their own NHibernate `Configuration` object i.e.

```
var configuration = new Configuration();

configuration.SetProperty(Environment.Dialect, "NHibernate.Dialect.MsSql2012Dialect");
configuration.SetProperty(Environment.ConnectionString, @"...");

config.UsePersistence<NHibernatePersistence>().UseConfiguration(configuration);
```

### Symptoms

The problem manifests itself in wrong schema generated by the installers. Depending on the container used, there might be two variations of symptoms:

1. The schema for the *all* the tables is incorrect. All the primary keys are non-clustered (only `TimeoutEntity` table should have a non-clustered PK)
2. The schema for the `TimeoutEntity` has a clustered PK (should be non-clustered) and the `TimeoutEntity_EndpointIdx` index has wrong column order

### Root cause

When passing an external configuration object, it is shared by all the persistence concerns and all the mappings are registered in it. The first installer that runs (the order depends on the container/version used), creates the schema for *all the persistence concerns*. The timeout installer uses a specialized schema creation class. Depending on the order, this specialized class can either
1. be used for all tables
2. be not used at all

### Proposed solution

1. Make sure all the installers use the specialized schema tool (`OptimizedSchemaUpdate`)
2. Make sure the substitutions done in `OptimizedSchemaUpdate` are only executed in context of the timeouts table
3. Log a warning if incorrect schema is detected

**Comment by SzymonPobiega** [comment]
Fix pending https://github.com/Particular/NServiceBus.NHibernate/pull/253

**Comment by SzymonPobiega** [comment]
Another related thing is that when the user provide the `Configuration` object then selective disable of schema update won't work because any installer would create the whole schema. A solution to both issues could be cloning the `Configuration` object via binary serialization...

**Comment by MarcinHoppe** [comment]
7.1.4, 7.0.6, and 6.2.8 patches are now released. Closing.
