### ISSUE TITLE
NullReferenceException when using strongly-typed configuration API of NHibernate

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.NHibernate#254]
Source: [GoogleGroups](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/866MabS3fR4/H6YtCPj_AAAJ)

Packages: NSB 6.1.2, NSB.NHibernate 7.1.1, NHibernate 4.0.4.4000, NSB.SqlServer 3.0.1.

The code below throws System.NullReferenceException, Object reference not set to an instance of an object :
```
            var hibernateConfig = new Configuration();

            hibernateConfig.DataBaseIntegration(database =>
            {
                database.ConnectionProvider<DriverConnectionProvider>();
                database.Driver<Sql2008ClientDriver>();
                database.Dialect<MsSql2008Dialect>();
                database.ConnectionStringName = Settings.PersistenceConnectionString;
                database.IsolationLevel = System.Data.IsolationLevel.Serializable;
            });

            configuration.
                UsePersistence<NHibernatePersistence>().
                UseConfiguration(hibernateConfig);
```

The old school stringly typed configuration works fine.

**Comment by DocJames** [comment]
For some reason I'm unable to add the files as .zip. So here are the source code and packages.

Thanks,
Jimmy

using System;
using NHibernate.Cfg;
using NHibernate.Connection;
using NHibernate.Dialect;
using NHibernate.Driver;
using NServiceBus;
using NServiceBus.Features;
using NServiceBus.Transport.SQLServer;
using NServiceBus.Persistence;
using NServiceBus.Persistence.NHibernate;

namespace Esb.Publisher.AggregatedPowerReadingEvent.v2_0
{
    public class EndpointConfig : IConfigureThisEndpoint
    {
        protected static readonly log4net.ILog Log = log4net.LogManager.GetLogger(typeof(EndpointConfig));

        public void Customize(EndpointConfiguration endpointConfiguration)
        {
            log4net.Config.XmlConfigurator.Configure();
            NServiceBus.Logging.LogManager.Use<Log4NetFactory>();

            Log.Info("Running EndpointConfig");

            endpointConfiguration.EnableInstallers();
            endpointConfiguration.UseSerialization<JsonSerializer>();

            ConfigureEndpoint(endpointConfiguration);
            ConfigureConventions(endpointConfiguration);
            ConfigureRecoverability(endpointConfiguration);
            ConfigureFeatures(endpointConfiguration);
            ConfigurePersistence(endpointConfiguration);
            ConfigureTransport(endpointConfiguration);
            ConfigureQueues(endpointConfiguration);

            Log.Info("EndpointConfig done");
        }

        private static void ConfigureEndpoint(EndpointConfiguration configuration)
        {
            configuration.DefineEndpointName(Settings.EndpointName);

            // Message processing concurrency
            int messageProcessingConcurrency;
            if (!string.IsNullOrWhiteSpace(Settings.MessageProcessingConcurrency) && int.TryParse(Settings.MessageProcessingConcurrency, out messageProcessingConcurrency))
            {
                configuration.LimitMessageProcessingConcurrencyTo(messageProcessingConcurrency);
            }
        }

        private static void ConfigureConventions(EndpointConfiguration configuration)
        {
            configuration.Conventions().DefiningMessagesAs(t => t.Namespace != null && Settings.MessageNamespaces.Contains(t.Namespace));
            configuration.Conventions().DefiningEventsAs(t => t.Namespace != null && Settings.EventNamespaces.Contains(t.Namespace));
            configuration.Conventions().DefiningCommandsAs(t => t.Namespace != null && Settings.CommandNamespaces.Contains(t.Namespace));
        }

        private static void ConfigureRecoverability(EndpointConfiguration configuration)
        {
            int immediateNumberOfRetries;
            int delayedNumberOfRetries;

            if (!int.TryParse(Settings.ImmediateNumberOfRetries, out immediateNumberOfRetries))
            {
                immediateNumberOfRetries = 1;
            }

            if (!int.TryParse(Settings.DelayedNumberOfRetries, out delayedNumberOfRetries))
            {
                delayedNumberOfRetries = 2;
            }

            var recoverability = configuration.Recoverability();

            recoverability.Immediate(
                immediate =>
                {
                    immediate.NumberOfRetries(immediateNumberOfRetries);
                });

            recoverability.Delayed(
                delayed =>
                {
                    delayed.NumberOfRetries(delayedNumberOfRetries);
                    delayed.TimeIncrease(TimeSpan.FromMinutes(5));
                });
        }

        private static void ConfigureFeatures(EndpointConfiguration configuration)
        {
            configuration.EnableFeature<TimeoutManager>();

            configuration.DisableFeature<Outbox>();
            configuration.DisableFeature<Scheduler>();
            configuration.DisableFeature<Sagas>();
        }

        public static void ConfigurePersistence(EndpointConfiguration configuration)
        {
            // Subscription storage cache
            int subscriptionStorageCacheInMinutes;
            if (string.IsNullOrWhiteSpace(Settings.SubscriptionStorageCacheInMinutes) || !int.TryParse(Settings.SubscriptionStorageCacheInMinutes, out subscriptionStorageCacheInMinutes))
            {
                subscriptionStorageCacheInMinutes = 5;
            }

            var hibernateConfig = new Configuration();

            // USING THIS SECTION DOES NOT WORK
            hibernateConfig.DataBaseIntegration(database =>
            {
                database.ConnectionProvider<DriverConnectionProvider>();
                database.Driver<Sql2008ClientDriver>();
                database.Dialect<MsSql2008Dialect>();
                database.ConnectionStringName = Settings.PersistenceConnectionString;
                database.IsolationLevel = System.Data.IsolationLevel.Serializable;
            });

            // USING THIS SECTION WORKS
            //hibernateConfig.SetProperty(NHibernate.Cfg.Environment.ConnectionProvider, "NHibernate.Connection.DriverConnectionProvider");
            //hibernateConfig.SetProperty(NHibernate.Cfg.Environment.ConnectionDriver, "NHibernate.Driver.Sql2008ClientDriver");
            //hibernateConfig.SetProperty(NHibernate.Cfg.Environment.Dialect, "NHibernate.Dialect.MsSql2008Dialect");
            //hibernateConfig.SetProperty(NHibernate.Cfg.Environment.ConnectionString, Settings.PersistenceConnectionString);
            //hibernateConfig.SetProperty(NHibernate.Cfg.Environment.DefaultSchema, "dbo");

            configuration
                .UsePersistence<NHibernatePersistence>()
                .UseConfiguration(hibernateConfig)
                .EnableCachingForSubscriptionStorage(TimeSpan.FromMinutes(subscriptionStorageCacheInMinutes));
        }

        public static void ConfigureTransport(EndpointConfiguration configuration)
        {
            var connectionString = Settings.TransportConnectionString;
            var transport = configuration.UseTransport<SqlServerTransport>();

            transport.ConnectionString(connectionString);
            transport.Transactions(TransportTransactionMode.TransactionScope);

            transport.DefaultSchema("dbo");
            transport.UseSchemaForQueue(Settings.ErrorQueue, "dbo");
            transport.UseSchemaForQueue(Settings.AuditQueue, "dbo");
        }

        public static void ConfigureQueues(EndpointConfiguration configuration)
        {
            configuration.AuditProcessedMessagesTo(Settings.AuditQueue, TimeSpan.FromMinutes(5)); // Audit messages TTL (time to live) is 5 minutes
            configuration.SendFailedMessagesTo(Settings.ErrorQueue);
        }
    }
}


<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Iesi.Collections" version="4.0.1.4000" targetFramework="net462" />
  <package id="log4net" version="2.0.7" targetFramework="net462" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net452" />
  <package id="NHibernate" version="4.0.4.4000" targetFramework="net462" />
  <package id="NServiceBus" version="6.1.2" targetFramework="net452" />
  <package id="NServiceBus.Host" version="7.0.0" targetFramework="net452" />
  <package id="NServiceBus.Log4Net" version="2.0.0" targetFramework="net462" />
  <package id="NServiceBus.NHibernate" version="7.1.1" targetFramework="net462" />
  <package id="NServiceBus.SqlServer" version="3.0.1" targetFramework="net462" />
  <package id="SeasNve.Enterprise.DataModel" version="1.0.52" targetFramework="net462" />
  <package id="SeasNve.Enterprise.ServiceModel" version="1.0.90" targetFramework="net462" />
  <package id="SeasNve.Integration.Core.Libraries" version="1.0.60" targetFramework="net452" />
  <package id="ServiceControl.Plugin.Nsb6.Heartbeat" version="2.0.0" targetFramework="net452" />
  <package id="SlowCheetah" version="2.5.15" targetFramework="net451" />
</packages>

**Comment by DocJames** [comment]
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Iesi.Collections" version="4.0.1.4000" targetFramework="net462" />
  <package id="log4net" version="2.0.7" targetFramework="net462" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net452" />
  <package id="NHibernate" version="4.0.4.4000" targetFramework="net462" />
  <package id="NServiceBus" version="6.1.2" targetFramework="net452" />
  <package id="NServiceBus.Host" version="7.0.0" targetFramework="net452" />
  <package id="NServiceBus.Log4Net" version="2.0.0" targetFramework="net462" />
  <package id="NServiceBus.NHibernate" version="7.1.1" targetFramework="net462" />
  <package id="NServiceBus.SqlServer" version="3.0.1" targetFramework="net462" />
  <package id="SeasNve.Enterprise.DataModel" version="1.0.52" targetFramework="net462" />
  <package id="SeasNve.Enterprise.ServiceModel" version="1.0.90" targetFramework="net462" />
  <package id="SeasNve.Integration.Core.Libraries" version="1.0.60" targetFramework="net452" />
  <package id="ServiceControl.Plugin.Nsb6.Heartbeat" version="2.0.0" targetFramework="net452" />
  <package id="SlowCheetah" version="2.5.15" targetFramework="net451" />
</packages>

**Comment by SimonCropp** [comment]
@DocJames could you also copy the stack trace and post it here

**Comment by DocJames** [comment]
Yep.


Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at NServiceBus.Persistence.NHibernate.NHibernateConfigurationBuilder.Build() in C:\BuildAgent\work\5135de308b2f3016\src\NServiceBus.NHibernate\Internal\NHibernateConfigurationBuilder.cs:line 49
   at NServiceBus.Features.NHibernateStorageSession.Setup(FeatureConfigurationContext context) in C:\BuildAgent\work\5135de308b2f3016\src\NServiceBus.NHibernate\SynchronizedStorage\NHibernateStorageSession.cs:line 43
   at NServiceBus.Features.FeatureActivator.ActivateFeature(FeatureInfo featureInfo, List`1 featuresToActivate, IConfigureComponents container, PipelineSettings pipelineSettings) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Features\FeatureActivator.cs:line 194
   at NServiceBus.Features.FeatureActivator.SetupFeatures(IConfigureComponents container, PipelineSettings pipelineSettings) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Features\FeatureActivator.cs:line 59
   at NServiceBus.InitializableEndpoint.<Initialize>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\InitializableEndpoint.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.GenericHost.<Start>d__1.MoveNext() in C:\Build\src\NServiceBus.Hosting.Windows\GenericHost.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Hosting.Windows.WindowsHost.Start() in C:\Build\src\NServiceBus.Hosting.Windows\WindowsHost.cs:line 30
   at Magnum.StateMachine.EventActionList`1.Execute(T stateMachine, Event event, Object parameter) in c:\Code\Topshelf\src\Topshelf\Internal\Hosts\ServiceHost.cs:line 0   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NServiceBus.Hosting.Windows.Program.Main(String[] args) in C:\Build\src\NServiceBus.Hosting.Windows\HostProgram.cs:line 149

**Comment by MarcinHoppe** [comment]
@DocJames This line here seems to be causing some trouble:

>  database.ConnectionStringName = Settings.PersistenceConnectionString;

The `database.ConnectionStringName` should be used to indicate which connection string from the `connectionStrings` section of the `App.config` file should be used. I'm guessing that the `Settings.PersistenceConnectionString` variable contains the full connection string:

> hibernateConfig.SetProperty(NHibernate.Cfg.Environment.ConnectionString, Settings.PersistenceConnectionString);

Can you change it to:

>  database.ConnectionString = Settings.PersistenceConnectionString;

And see if it helps?

**Comment by DocJames** [comment]
@MarcinHoppe Christ, yes, that is the problem. The Settings.PersistenceConnectionString is the whole connection string. I thought I was going crazy ...

Thanks for you good eyes and help! :)

**Comment by MarcinHoppe** [comment]
@DocJames Good to be a rubber 🦆 :). I'm closing this issue.
