### ISSUE TITLE
v7 for NSB core v6 doesn't use CombGuids for TimeoutEntity any more

### ISSUE THREAD

**Issue by cremor** [Particular/NServiceBus.NHibernate#260]
I noticed that with the big change for NSB core v6 the method `TimeoutPersister.Add()` was changed from using the method `GenerateCombGuid()` to just use `Guid.NewGuid()`. Was this done on purpose?

I think this is wrong since now the primary key isn't an increasing value any more which could cause performance problems in MS SQL server.

Note: If you reintroduce the CombGuid, don't just add the method from before again. This method has the daylight saving time bug described in Particular/NServiceBus#4195. Either copy the fixed code from core or let NHibernate do the work by as shown in #113

**Comment by MarcinHoppe** [comment]
Thanks for reporting this. We are working on the fix.

**Comment by MarcinHoppe** [comment]
@cremor Just to let you know, we released the following patches that address this problem:

- https://github.com/Particular/NServiceBus.NHibernate/releases/tag/7.1.3
- https://github.com/Particular/NServiceBus.NHibernate/releases/tag/7.0.5
