### ISSUE TITLE
Not creating tables in correctly on first run

### ISSUE THREAD

**Issue by dasjestyr** [Particular/NServiceBus.NHibernate#261]
I just ran my app in a new environment and it didn't seem to create the new tables correctly. Using the same settings as I used in the other environment, it seems to have created the tables for sagas, outbox, and subscription as the domain user name:

![image](https://cloud.githubusercontent.com/assets/3200529/22856254/3bcedf6a-f04b-11e6-99db-27be8cd90226.png)

My connection string is using trusted connection and I have no custom settings for default schema. It is being set in web.config connection strings.

**Comment by dasjestyr** [comment]
not sure if related to https://github.com/Particular/NServiceBus.NHibernate/issues/252

**Comment by MarcinHoppe** [comment]
@dasjestyr The SQL Server transport will default to `dbo` as the default schema but the NHibernate persister will default to whatever default schema is configured for the user.

Can you check the default schema for the user that created the tables by issuing this query in SQL Server Management Studio:

`SELECT SCHEMA_NAME()`

Please make sure that you connect to the database as the same user that was used to run the endpoint to create the tables.

**Comment by dasjestyr** [comment]
So funny story... I can't log into the database under that user because of some funky auth federation setup. The app box can, but I can't.  I can verify however that no default schema was selected when that service account was created. In the meanwhile, I've assigned dbo as the default schema for the group that has access to that database and corrected the table ownership that was generated by NHibernate by hand. I'll keep this in mind for the future. Thanks!
