### ISSUE TITLE
Use TransactionScope for outbox transaction

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.NHibernate#274]
Allow Outbox to run in `TransactionScope` mode rather than using native transaction. This would be a a very specific feature for legacy integration scenarios where:
 * There is a legacy database which schema can't be changed (e.g. by adding Outbox table
 * There is no other way to achieve idempotency

In this scenario the Outbox table would be in a new database. The Outbox transaction could be escalated to DTC to span the new database and the legacy database. The outbox records would be stored in the new database.

The scenario was supported in NServiceBus Version 5 (persister Version 6) and is broken since Version 6/7.

**Comment by MarcinHoppe** [comment]
I'm thinking that this should be moved to PlatDev because it spans more than one repo (potential interactions with the transport) and a fair amount of doco and guidance on when to use it, etc.

**Comment by SzymonPobiega** [comment]
@MarcinHoppe I don't think this spans multiple repos. It should be transport-agnostic and only based on existance of TransactionScope.

**Comment by ramonsmits** [comment]
It is not required for using MSDTC is all. TransactionScope != MSDTC, which is assumed by most. It is perfectly fine to use the lightweight transaction manager by using TransactionScope without any promotion to a distributed transaction. This results in much cleaner DB code that doesn't require passing any connection/transaction objects around.

**Comment by SzymonPobiega** [comment]
We had a customer case about upgrading from 5 to 7 and this missing feature is a blocker. Additionally, with removing support of transaction scopes in Outbox we lost easy way of setting the transaction isolation level on the outbox connection.

**Comment by SzymonPobiega** [comment]
@Particular/developer-experience-squad is this something that you can take on?

**Comment by sergioc** [comment]
> is broken since Version 6/7.

Given this is a broken feature, could @Particular/keeping-the-lights-on-squad be a better fit to handle this?

**Comment by SzymonPobiega** [comment]
@sergioc I think this is a missing feature, not a bug. Looking at the [triage](https://github.com/Particular/PlatformDevelopment/blob/master/guidelines/triage.md#priority-matrix) it does not fit there.

**Comment by sergioc** [comment]
@SzymonPobiega it is missing, but if we used to have the feature, why isn't it considered broken?

**Comment by Scooletz** [comment]
KtLO mode on.
The fact that something has been removed does not imply, that the current version is broken. It might have been removed because of various reasons. If there was no reason, and it was just forgotten, it still does not fit our triage criteria as:

> A bug is a flaw in the software that causes it to produce incorrect or unexpected results

With no capability there are no incorrect/unexpected results. This is lack of a feature.

**Comment by SzymonPobiega** [comment]
Fixed in #439
