### ISSUE TITLE
Not awaited tasks in CachedSubscriptionPersister

### ISSUE THREAD

**Issue by cremor** [Particular/NServiceBus.NHibernate#288]
While reading through your code I noticed that you don't await the base calls of `Subscribe` and `Unsubscribe` in `CachedSubscriptionPersister`. This doesn't affect runtime behavior because the base methods are synchronous, but the calls should still be awaited, right?

**Comment by danielmarbach** [comment]
Yes they should. When the retry happens a [Task.Delay](https://github.com/Particular/NServiceBus.NHibernate/blob/develop/src/NServiceBus.NHibernate/Subscriptions/SubscriptionPersister.cs#L98) will be used and then the retry of the function call will be scheduled on a continuation. In that case the function will not be executed synchronously. Good catch.

@Particular/nhibernate-persistence-maintainers see above

**Comment by DavidBoike** [comment]
Particular.CodeRules 0.2.0 was just released to NuGet, which includes the new analyzer to detect dropped tasks. Suggest we update that in NH.

**Comment by cremor** [comment]
> When the retry happens a Task.Delay will be used and then the retry of the function call will be scheduled on a continuation. In that case the function will not be executed synchronously.

This is an yet unreleased change, right? Because both the master branch and the 7.2.0 tag don't have the retry yet. They are really synchronous there.

**Comment by SzymonPobiega** [comment]
@cremor yes, the `develop` branch contains the change which is not yet released. It adds a retry logic to `Subscribe` and `Unsubscribe` calls to account for possible concurrency errors when an endpoint is scaled out and multiple instances want to access the subscription store at the same time.

**Comment by SzymonPobiega** [comment]
Addressed in https://github.com/Particular/NServiceBus.NHibernate/pull/289. Thanks a lot @cremor !
