### ISSUE TITLE
Update docs and samples for ConnectionStringName

### ISSUE THREAD

**Issue by dbelcham** [Particular/NServiceBus.NHibernate#302]
v7 of NServiceBus Core has deprecated the use of `ConnectionStringName`. Docs, snippets and samples will need to be updated to remove the use of this capability. More info on what the alternative is can be found in https://docs.particular.net/nservicebus/upgrades/6to7/ once https://github.com/Particular/docs.particular.net/pull/3126 has been merged.

**Comment by SzymonPobiega** [comment]
There are no more usages of `ConnectionStringName` in the documentation as of 2020-06-17.
