### ISSUE TITLE
Update to NHibernate 5.0

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus.NHibernate#313]
[NHibernate 5.0](http://nhibernate.info/blog/2017/10/10/nhibernate-5-0-released.html) has been released and will probably want to update at one point.

@SimonCropp has already contributed a PR: #312.

**Comment by danielmarbach** [comment]
This has been fixed as part of the [8.1 release](https://github.com/Particular/NServiceBus.NHibernate/releases/tag/8.1.0)
