### ISSUE TITLE
NServiceBus doesn't automatically create schema (SQL Server)

### ISSUE THREAD

**Issue by chezih** [Particular/NServiceBus.NHibernate#486]
Please look at this question:
https://stackoverflow.com/questions/60409150/nservicebus-doesnt-automatically-create-schema-sql-server

Why NSB doesn't create schema if it not exist?

**Comment by adamralph** [comment]
@chezih it would better to raise your question in our [discussion group](https://discuss.particular.net/) which has a much larger audience than this repo and is designed for Q&A.

Or alternatively, you can request support using one of the other methods listed at https://particular.net/support
