### ISSUE TITLE
Make the caching on by default

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.NHibernate#53]
https://github.com/Particular/NServiceBus.NHibernate/pull/33

**Comment by SzymonPobiega** [comment]
@andreasohlund do you think it should go with the V7 release? I find it hard to come up with a decent default for the cache.

**Comment by andreasohlund** [comment]
I don't think this is a must have for v7

Regarding the default time it seems like something small like 5-10s would give the wanted perf boost?

**Comment by SzymonPobiega** [comment]
OK. Let's pause it then and come back after V6 release.

**Comment by ramonsmits** [comment]
I already stress tested this and there is not a huge gain between one second or 10. If we do use this we should log with INFO level visible during startup that we are caching the results.

**Comment by SzymonPobiega** [comment]
The SQL persistence took the approach to require the cache duration to be provided (a mandatory setting). Given we don't plan to release a major version of NH in near future and that SQL persistence is preferred for new systems I am closing this one. @andreasohlund feel free to re-open if you disagree.
