### ISSUE TITLE
Order of settings

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.NHibernate#66]
Values provided by users in ConfigSection should take precedence over values provided with Fluent API, while Fluent API overrides default values set by ConfigSeaction.

ConfigSection defaults --> Fluent API --> CofnigSection user values

**Comment by SzymonPobiega** [comment]
Which particular values? I think we made some progress with regards to how config is handled.

**Comment by SzymonPobiega** [comment]
@SeanFeldman do you remember which particular settings you had in mind?

**Comment by SeanFeldman** [comment]
Being 2 years ago, you'd have to torture me and event then, I'm afraid I wouldn't break... just can't recall what was the issue. I vaguely suspect that it was not for NSB.NHibernate. You know, being a spy and such, need to cover my traces... :smile: 
Will close this.
