### ISSUE TITLE
NHibernateStorageContext is null if no saga is defined in the endpoint.

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.NHibernate#71]
Scenario:

* endpoint using Sql Server as Transport and NHibernate as persistence;
* the endpoint wants to run in No-Dtc mode;
* a message handler expects to have a dependency on `NHibernateStorageContext`;

`NHibernateStorageContext` is always null.

Bug:

the `NHibernateStorageContext`is registered in the container by the `NHibernateStorageSession` feature but the feature is configured to depend on at least one of the followings: `NHibernateSagaStorage` or `NHibernateOutboxStorage`.

The above means that if a Saga is defined in the endpoint, even a dummy one, the feature is enabled, otherwise no and `NHibernateStorageContext` is always null.

**Comment by johnsimons** [comment]
@andreasohlund should this go out in a patch release for v6 ?

**Comment by andreasohlund** [comment]
My knee jerk is that this can be v6.1 for now

**Comment by johnsimons** [comment]
@andreasohlund can we discuss this change, after starting working on it I'm now wondering if we should do it or not.
The following issues I have identified:
- The connection string needs to be in a specific key
- This is only needed if using Outbox or in a saga handler
- User needs to pass a `NHibernate.Cfg.Configuration`

**Comment by SzymonPobiega** [comment]
Done via https://github.com/Particular/Requirements/issues/258
