### ISSUE TITLE
Incorrect assembly version

### ISSUE THREAD

**Issue by rosieks** [Particular/NServiceBus.NHibernate#76]
I just wanted to updated NServiceBus.NHibernate to version 4.5.3 and still using NSB 4.2

According to nuget package it's possible, but when I try to build my project I receive the following error:
```
Assembly 'NServiceBus.NHibernate, Version=4.5.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c' uses 'NServiceBus.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c' 
which has a higher version than referenced assembly 
'NServiceBus.Core, Version=4.2.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c'	c:\Users\sr6111\Documents\Visual Studio 2013\Projects\ConsoleApplication2\packages\NServiceBus.NHibernate.4.5.3\lib\net40\NServiceBus.NHibernate.dll	ConsoleApplication2
```
It would be great if I could upgrade only NHibernate part without the whole NSB.

**Comment by SimonCropp** [comment]
@rosieks have you tried a binding redirect?

**Comment by rosieks** [comment]
Yes, but I still get this message while building project

**Comment by johnsimons** [comment]
@rosieks that is a bug in the nuget specs, the specs should be >=4.4

**Comment by johnsimons** [comment]
Fixed in https://github.com/Particular/NServiceBus.NHibernate/commit/091c48f4610ae386b4a2642b9b223308493c0836
