### ISSUE TITLE
v6.0.1 src included in NuGet package

### ISSUE THREAD

**Issue by Henrik-R** [Particular/NServiceBus.NHibernate#82]
In the NuGet for v6.0.1 there is a src folder included in the NuGet package containing what seems to be the entire source code. 

This is not the case for any the other 5 NServiceBus NuGet packages I have used.

If this was intentional I apologize for the disruption

Regards, Henrik

**Comment by johnsimons** [comment]
I don't think we need it, we will remove it in future releases

**Comment by johnsimons** [comment]
Addressed in https://github.com/Particular/NServiceBus.NHibernate/commit/fe25d2be8d992886d36ab7b895e5b33ee62f3ea3
