### ISSUE TITLE
Honor the unique properties in the saga metamodel

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.NHibernate#83]
The new metamodel in core v6 contains the properties that are unique. The persister should honor this.

This is how the InMemory persister is currently doing it

https://github.com/Particular/NServiceBus/issues/346

**Comment by andreasohlund** [comment]
@DavidBoike this is done right?

**Comment by DavidBoike** [comment]
Yep, NH for Core V6 makes its unique indexes off the saga metadata, honoring those props.
