### ISSUE TITLE
Make Connection resilient

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.NHibernate#85]
When DB connection goes down the connection is not reestablished. I think it would be a good improvement to introduce connection resilience. For example

http://weblogs.asp.net/ricardoperes/nhibernate-connection-resiliency

I didn't have a detailed look at the code. I think it is not there yet.

@SzymonPobiega thoughts?

**Comment by danielmarbach** [comment]
Update: Seems to be coming in NH 5 with the framework https://nhibernate.jira.com/browse/NH-3607

**Comment by SzymonPobiega** [comment]
Do you know what is the timeframe for V5?

**Comment by danielmarbach** [comment]
nope

**Comment by ramonsmits** [comment]
When the connection goes down then the transaction is gone right? We already have FLR and SLR that results in similar behavior.

I can understand that this is a nice feature from a non transactional client perspective when doing Bus.Send() and using the SQL transport.

Is this the scenarios you have in mind for this improvement?

**Comment by SzymonPobiega** [comment]
I agree with @ramonsmits that FLR covers this. Feel free to re-open if you disagree.
