### ISSUE TITLE
Controling the length of the Saga property/column in SQL Server

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.NHibernate#87]
This is coming from a customer case

> We have seen that SQL DB columns are created with 255 as length in a Saga table (we use nhibernate persistence). Is there any way to increase or decrease it? I would prefer an attribute like [Unique] to control it.

My workaround:

> Add a custom `YourSagaData.hbm.xml` as an embedded resource to your project containing the saga data as described here
> http://stackoverflow.com/questions/25577582/modifying-how-nhibernate-saves-saga-data-in-nservicebus

Answer:

> We have changed the length of column manually in the DB. Anyway, this table has to be scripted for production deployment, so this method works. I am aware that table has to be dropped and recreated if there are any changes to saga and we should do this change again.
> The problem with XML is that we have to create it manually and maintain it for all the properties of Saga which is tedious job. I still see a case for attribute in future versions of NSB.

My answer:

> Thanks for the feedback. How about we open up the NHibernate implementation to be able to pass in custom code mappings for sagas? Would that be more appropriate?

Answer:

> Custom code mapping is better than XML, perhaps. That would also mean that I have to map each and every property. I still think attribute is simple, quick way of doing things. I guess, developers have not got rid of attributes completely in todays’ programming world. We have them in MVC controllers, view models, code-first approach (models). WCF uses them. NSB has [Unique] attribute!!! And the list continues…

I'm very unsure about this. Here is my answer to the customer:

> Thank you very much about your feedback. Because we strive to have a consistent platform it is very difficult to come up with a solution which fits all persistence layers. The unique attribute is something which is in the core. All persistence layers understand it. Introducing an attribute to define the column length as an attribute is something we could only do in the NH implementation because all other persistence layers might not known the concept of a column.I'll add your suggestion to the feature pipeline and we'll be giving it more thought. Keep the feedback coming, we highly appreciate it.

I'm raising this as a dicussion point. @SzymonPobiega thoughts?

**Comment by SzymonPobiega** [comment]
@danielmarbach I think that the custom mapping sample covers all the angles https://docs.particular.net/samples/nhibernate/custom-mappings/. Feel free to re-open if you disagree.
