### ISSUE TITLE
Problem inserting in NServiceBus table TimeoutEntity (Oracle database)

### ISSUE THREAD

**Issue by mlunacant** [Particular/NServiceBus.NHibernate#88]
I have a saga trying to send a timeout message this way

<code>RequestTimeout < MyTimeout > (mydatetime);</code>

after that and excepcion is thrown, it seems there is a problem inserting in the TimeoutEntity table and I guess the problem appairs because the data for Headers column is too large

2015-03-05 15:14:45.562 INFO  NServiceBus.Unicast.Transport.TransportReceiver Fa
iled to process message
NHibernate.Exceptions.GenericADOException: could not insert: [NServiceBus.Timeou
tPersisters.NHibernate.TimeoutEntity#5029ec50-aaa5-48b9-9c8c-a45200fb3f02][SQL:
INSERT INTO TimeoutEntity (Destination, SagaId, State, Time, Headers, Endpoint,
Id) VALUES (?, ?, ?, ?, ?, ?, ?)] ---> Oracle.ManagedDataAccess.Client.OracleExc
eption: ORA-01461: can bind a LONG value only for insert into a LONG column
   at OracleInternal.ServiceObjects.OracleCommandImpl.VerifyExecution(OracleConn
ectionImpl connectionImpl, Int32& cursorId, Boolean bThrowArrayBindRelatedErrors
, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean b
FirstIterationDone)

We are using this references
Oracle driver (odp.net v 12.1.021)
NHibernate (v 4.0.3.4000)
NServiceBus.NHibernate (v 6.1.0)

Best Regards,
Miguel

**Comment by johnsimons** [comment]
@mlunacant any chance you can help me reproduce this issue ?
A small repro would be awesome ?

**Comment by pablocastilla** [comment]
@johnsimons Here you are.

https://github.com/pablocastilla/NSB_NHIBERNATE_ORACLE_PROBLEM 

Please, tell me if you have problems with it.

**Comment by johnsimons** [comment]
@pablocastilla thanks for the repro.
I can replicate it using the drivers you included, but if I change to use Oracle.DataAccess.dll, then it works.
`Oracle.DataAccess.dll` is the driver we use in our testing, it is shipped with oracle and you should be able to find it in [installation_path]\app\oracle\product\11.2.0\server\odp.net\bin\4

**Comment by johnsimons** [comment]
I think this thread is related - https://community.oracle.com/thread/3674405

**Comment by johnsimons** [comment]
@pablocastilla can you try the Oracle.DataAccess.dll ?
You need to set  `connection.driver_class = "NHibernate.Driver.OracleDataClientDriver"`

**Comment by johnsimons** [comment]
ping @pablocastilla, any news ?

**Comment by pablocastilla** [comment]
It is a driver problem. Oracle told us that it will be solved in April, so we have changed to InMemory until the fix is released (we are not going to production until next year, we can wait :)) .

**Comment by johnsimons** [comment]
@pablocastilla that is kind of good news.
The other option is to use the driver I mention above ?

**Comment by johnsimons** [comment]
@pablocastilla in this case are you happy with me closing this one ?

**Comment by pablocastilla** [comment]
To be honest I tried to make the other driver work but I couldn't, but at the same time Oracle answered the question so I leave the problem.

I am happy if you close this one, it is an oralce issue.
