### ISSUE TITLE
Outbox is broken when using with Oracle

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus.NHibernate#90]
Release v6.1 included #79, which unfortunately broke Outbox when used with an Oracle database.

@SzymonPobiega I need your help to fix this ?

Need to investigate the impact of this issue

**Comment by SzymonPobiega** [comment]
@johnsimons I'll investigate

**Comment by johnsimons** [comment]
@SzymonPobiega you need to install "Oracle Database 11g Express Edition".

**Comment by johnsimons** [comment]
@SzymonPobiega any news on this ? Should we pair today ?

**Comment by johnsimons** [comment]
@SzymonPobiega is this fixed now ? Do we backport it ?

**Comment by SzymonPobiega** [comment]
it was introduced in 6.1.0 and 6.1.1 is going to fix it so no backporting needed. All the acceptance tests are [passing](http://builds.particular.net/viewLog.html?buildId=102371&tab=buildResultsDiv&buildTypeId=NServiceBusNHibernate_2AcceptanceTests) on MSMQ (both SQL Server and Oracle). There are problems with acceptance test for SQL Server transport and Oracle persistence but the [failures](http://builds.particular.net/viewType.html?buildTypeId=NServiceBusNHibernate_AcceptanceTestsSqlServer&branch_NServiceBusNHibernate=hotfix-6.1.1&tab=buildTypeStatusDiv) seem to be random.

I was hesitant with releasing it because I wanted to replace the behavior with [258](https://github.com/Particular/Requirements/issues/258). I believe it is more appropriate. What do you think?

**Comment by johnsimons** [comment]
@SzymonPobiega would you like me to see why the tests are failing for SQL Server transport and Oracle persistence ?

**Comment by SzymonPobiega** [comment]
@johnsimons in [that comment](https://github.com/Particular/NServiceBus.NHibernate/issues/71#issuecomment-69288059) you mentioned problems with always exposing the context. Could you evaluate if my proposal solves these problems and we can go forward?

**Comment by SzymonPobiega** [comment]
@johnsimons yeah, if you could take a look it would be awesome

**Comment by johnsimons** [comment]
@SzymonPobiega found an issue, it looks like the SqlServer transport expects an error queue configuration even in sendonly mode, this is the error:
```
System.Configuration.ConfigurationErrorsException: Faults forwarding requires an error queue to be specified. Please add a 'MessageForwardingInCaseOfFaultConfig' section to your app.config
 or configure a global one using the powershell command: Set-NServiceBusLocalMachineSettings -ErrorQueue {address of error queue}
   at NServiceBus.Features.ErrorQueueSettings.GetConfiguredErrorQueue(ReadOnlySettings settings) in c:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\ErrorQueueSettings.cs:line 45
   at NServiceBus.Features.SqlServerTransportFeature.Configure(FeatureConfigurationContext context, String connectionStringWithSchema) in c:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\Config\SqlServerTransportFeature.cs:line 63
   at NServiceBus.Transports.ConfigureTransport.Setup(FeatureConfigurationContext context) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Transports\ConfigureTransport.cs:line 44
```

I've raised an issue for it in https://github.com/Particular/NServiceBus.SqlServer/issues/78

**Comment by johnsimons** [comment]
Both `When_handler_throws.Should_receive_exception_from_handler` and `When_handler_throws_AggregateException.Should_receive_exact_AggregateException_exception_from_handler` are doing asserts on specific stacktrace text, and because we modify the pipeline based on configuration settings those tests cannot ever pass!

Not sure how to handle this, IMHO, those tests are constantly giving us grief, I would remove them from the AT suite.

@SzymonPobiega @andreasohlund @SimonCropp thoughts ?

**Comment by SzymonPobiega** [comment]
@johnsimons but why do these stack trace tests pass for SQL Server and fail with Oracle?

**Comment by johnsimons** [comment]
I don't think they do, can you run them ?

**Comment by SzymonPobiega** [comment]
All the failures in [NHibernate+SQLServer transport suite](http://builds.particular.net/viewLog.html?buildId=103150&tab=buildResultsDiv&buildTypeId=NServiceBusNHibernate_AcceptanceTestsSqlServer) come from oracle dll: `NServiceBus.NHibernate.AcceptanceTests-Oracle.dll`

**Comment by johnsimons** [comment]
Unfortunately that doesn't mean much, run the tests locally to ensure, and
compare the stacktraces.
We have had false positives before :(

**Comment by johnsimons** [comment]
@SzymonPobiega when is this fix going to go out ?

**Comment by SzymonPobiega** [comment]
I'll be working on it this afternoon. Should be enough. The other thing is, remember the `if` statement that you didn't like? The nasty one that checked if you are on SQL transport with SQL persistence and outbox etc. I replaced it with implementation of https://github.com/Particular/Requirements/issues/258 and raised a concern but that one is not yet approved.

We can either go back to the old if or wait for it to be approved. The last thing to be done seems to be fixing the customer communication which Udi pointed out is not fully understandable.

**Comment by johnsimons** [comment]
@SzymonPobiega what version is this going out in ?

**Comment by SzymonPobiega** [comment]
6.1.1

**Comment by SzymonPobiega** [comment]
Let's bundle it to 6.2.0 because I don't see to release 2 versions, one after another.
