### ISSUE TITLE
Custom Interceptors and Conventions with Default Config Improvement

### ISSUE THREAD

**Issue by acgentry** [Particular/NServiceBus.NHibernate#95]
Hi there,

This may be a RTFM moment but I believe this does not exist out of the box in the current feature set.

If I want to add an Interceptor (i.e. Date Logic) or define a Convention (i.e. string property -> nvarchar(max)) I have to jump through a lot of hoops to create a config that matches the default behavior of NServiceBus.NHibernate module, in the end I couldn't get it to work perfectly (child arrays wouldn't populate) and so I think this would make a case for a good improvement to enable the injection of Interceptors and custom Conventions into the default configuration.

If this already exists, I do apologize, but I would love to help improve the documentation or learn from this experience.

Regards,
Adam

**Comment by johnsimons** [comment]
@acgentry would you like to start a PR and we can interact on it ?

**Comment by SzymonPobiega** [comment]
I believe the custom mapping documentation covers all the angles now: https://docs.particular.net/samples/nhibernate/custom-mappings/. Feel free to re-open if you disagree.
